### ISSUE TITLE
Migrate from legacy infrastructure on Travis-CI

### ISSUE THREAD

**Issue by theopak** [Cimpress-MCP/oauth_reverse_proxy#10]
Every build on Travis has this message:

> This job is running on our legacy infrastructure. Please read our docs on how to upgrade http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

That doc seems to suggest that making the change will result in a small speed improvement for builds. I think we should consider it.

**Comment by ryanbreen** [comment]
Agreed.  I didn't at the time because I needed sudo to install some of the dev tools used for the client tests.  That's not a good enough reason to avoid migrating, though.

**Comment by theopak** [comment]
Fixed in PR #12.
