### ISSUE TITLE
Release 1.5.10

### ISSUE THREAD

**Issue by theopak** [Cimpress-MCP/oauth_reverse_proxy#14]
Ryan, when you push a new tag so that Travis_CI publishes a [release](https://github.com/Cimpress-MCP/oauth_reverse_proxy/releases) to https://www.npmjs.com/package/oauth_reverse_proxy you may want to remove the "1.5.10**-2**" designator in the package.json file. I added that arbitrarily while messing around with the build process.

**Comment by ryanbreen** [comment]
The publication failed: https://travis-ci.org/Cimpress-MCP/oauth_reverse_proxy/builds/84115631

@theopak, can you fix-up .travis.yml to resolve this?  I added you as a collaborator in the NPM project, so you should be able to publish with your creds.

**Comment by theopak** [comment]
Ok. The error in build log tail looks like a simple fix.

``` bash
Deploying application
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
-npm ERR! publish Failed PUT 401
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.7/bin/node" "/home/travis/.nvm/versions/node/v0.12.7/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E401
npm ERR! You must be logged in to publish packages : oauth_reverse_proxy
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/Cimpress-MCP/oauth_reverse_proxy/npm-debug.log
No stash found.
Done. Your build exited with 0.
```

**Comment by ryanbreen** [comment]
Still no dice: https://travis-ci.org/Cimpress-MCP/oauth_reverse_proxy/builds/84137506

Feel free to iterate on this directly, no need for PRs or waiting for me to push.  Just make sure you do:

```
git tag -f v1.5.10
git push --tags --force
```

to keep re-attempting a push of 1.5.10.  This is a rare case where I'm not worried by `--force` options.

**Comment by theopak** [comment]
See change here: https://github.com/Cimpress-MCP/oauth_reverse_proxy/commit/7cc8f597833c4a27a7e32a1422d4c8cddfb99ebf

The issue preventing Travis-CI from deploying to NPM is that I encrypted my npm login with respect to the wrong Travis-CI repo. My npm key was encrypted for my user repo build, not the org. [The deploy worked](https://travis-ci.org/Cimpress-MCP/oauth_reverse_proxy/builds/84154091#L2737) after making this change: 

``` bash
$ npm login
Username: theopak
Password: 
Email: (this IS public) mail@theopak.com
$ cat ~/.npmrc
//registry.npmjs.org/:_authToken=<my-api-key>
registry=https://registry.npmjs.org/
$ travis encrypt -r Cimpress-MCP/oauth_reverse_proxy --add deploy.api_key <my-api-key>
$ git commit -am "v1.5.10"
$ git tag -f v1.5.10
$ git push <Cimpress-MCP origin> master --tags --force
```
