### ISSUE TITLE
Requests silently fail when they do not have charset === `utf-8` (with the dash)

### ISSUE THREAD

**Issue by theopak** [Cimpress-MCP/oauth_reverse_proxy#15]
Ever since our upgrade (we went body-parser 1.0.2->1.14.0) in PR #12, `body_parser.urlencoded()` middleware throws an error response for content that is not charset === `utf-8` (with the dash). This is blocking GH-14.

Relevant file: https://github.com/theopak/oauth_reverse_proxy/blob/538607c70720461b98848307c5498e96cd2e8e4a/lib/proxy/mutators/urlencoded_bodyparser.js

**Comment by theopak** [comment]
TODO
- [ ] add pre-mutator to stash original content type
- [x] add post-mutator to restore original content type
- [ ] add unit tests

**Comment by theopak** [comment]
See https://github.com/theopak/oauth_reverse_proxy/tree/bug/GH-15

**Comment by ryanbreen** [comment]
The pre- and post- can be in the same mutator.  Stash the variable from `req` in the parent closure.  Delete from `req`.  In the body_parser callback, reset the `req` variable in the callback before calling `next()`.

**Comment by theopak** [comment]
Good point, I like that approach better because it guarantees that the extra mutators are called only in the case of them being needed.

**Comment by theopak** [comment]
Moving issue to the PR: https://github.com/Cimpress-MCP/oauth_reverse_proxy/pull/16
